plugins {
    id 'com.android.application'
}

android {
    namespace 'at.away23.novablock.compat'
    compileSdk 36

    defaultConfig {
        applicationId 'at.away23.novablock.compat'
        minSdk 21
        targetSdk 36
        versionCode 3
        versionName '1.0.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
