(()=>{'use strict';const N=window.NB,S=N.state,$=N.$;
const boardEl=$('board'),boardWrap=$('boardWrap'),particles=$('particles'),clearFlash=$('clearFlash'),trayEl=$('tray');
N.shapeBounds=s=>({w:Math.max(...s.map(p=>p[0]))+1,h:Math.max(...s.map(p=>p[1]))+1});
N.randomPiece=()=>({shapeId:Math.floor(S.rng()*N.SHAPES.length),colorIndex:1+Math.floor(S.rng()*5),used:false,id:Math.random().toString(36).slice(2)});
N.buildBoard=()=>{boardEl.innerHTML='';S.cells=[];for(let i=0;i<64;i++){const c=document.createElement('div');c.className='cell';c.dataset.i=i;c.onpointerdown=e=>{if(S.blast&&S.board[i]){e.preventDefault();N.useBlast(i)}};boardEl.appendChild(c);S.cells.push(c)}N.renderBoard()};
N.renderBoard=()=>{for(let i=0;i<64;i++){const c=S.cells[i],v=S.board[i];c.classList.toggle('filled',!!v);c.style.setProperty('--block',v?N.blockColor(v):'transparent');if(!v)c.classList.remove('clearing','blastTarget','preClear')}};
N.refill=()=>{S.pieces=[N.randomPiece(),N.randomPiece(),N.randomPiece()];N.renderTray();N.saveActive()};
N.renderTray=()=>{trayEl.innerHTML='';S.pieces.forEach((p,index)=>{const slot=document.createElement('div');slot.className='pieceSlot'+(p.used?' used':'');const el=document.createElement('div');el.className='piece';const sh=N.SHAPES[p.shapeId],b=N.shapeBounds(sh),unit=innerHeight<760?23:28;el.style.gridTemplateColumns=`repeat(${b.w},${unit}px)`;el.style.gridTemplateRows=`repeat(${b.h},${unit}px)`;el.style.setProperty('--block',N.blockColor(p.colorIndex));for(let y=0;y<b.h;y++)for(let x=0;x<b.w;x++){const m=document.createElement('div');if(sh.some(q=>q[0]===x&&q[1]===y))m.className='mini';m.style.gridColumn=x+1;m.style.gridRow=y+1;el.appendChild(m)}if(!p.used)el.onpointerdown=e=>N.startDrag(e,index,el);slot.appendChild(el);trayEl.appendChild(slot)})};
N.canPlace=(sh,row,col)=>sh.every(([x,y])=>{const r=row+y,c=col+x;return r>=0&&r<8&&c>=0&&c<8&&!S.board[r*8+c]});
function clearGhost(){for(const i of S.lastGhost){const c=S.cells[i];if(c){c.classList.remove('ghost','bad');c.style.removeProperty('--ghost')}}S.lastGhost=[]}
function ghost(sh,row,col,color,valid){clearGhost();for(const [x,y] of sh){const r=row+y,c=col+x;if(r>=0&&r<8&&c>=0&&c<8){const i=r*8+c,e=S.cells[i];e.classList.add(valid?'ghost':'bad');e.style.setProperty('--ghost',color);S.lastGhost.push(i)}}}
function geo(){const rect=boardEl.getBoundingClientRect(),gap=4,pad=7,cell=(rect.width-pad*2-gap*7)/8;return{rect,gap,pad,cell,step:cell+gap}}
function raw(x,y,sh,g){const b=N.shapeBounds(sh),pw=b.w*g.cell+(b.w-1)*g.gap,ph=b.h*g.cell+(b.h-1)*g.gap;return{col:Math.round((x-g.rect.left-g.pad-pw/2)/g.step),row:Math.round((y-g.rect.top-g.pad-ph/2)/g.step)}}
function center(row,col,sh,g){const b=N.shapeBounds(sh),pw=b.w*g.cell+(b.w-1)*g.gap,ph=b.h*g.cell+(b.h-1)*g.gap;return{x:g.rect.left+g.pad+col*g.step+pw/2,y:g.rect.top+g.pad+row*g.step+ph/2}}
function nearest(sh,x,y,g){const reach=g.step*1.8;if(x<g.rect.left-reach||x>g.rect.right+reach||y<g.rect.top-reach||y>g.rect.bottom+reach)return null;const q=raw(x,y,sh,g);let best=null,d0=1e9;for(let dr=-2;dr<=2;dr++)for(let dc=-2;dc<=2;dc++){const row=q.row+dr,col=q.col+dc;if(!N.canPlace(sh,row,col))continue;const p=center(row,col,sh,g),d=Math.hypot(p.x-x,p.y-y);if(d<d0){d0=d;best={row,col,valid:true}}}return best&&d0<=g.step*1.85?best:{row:q.row,col:q.col,valid:N.canPlace(sh,q.row,q.col)}}
N.startDrag=(e,index,el)=>{if(S.busy||S.blast||S.pieces[index].used)return;e.preventDefault();N.sfx('pickup',.42,1.06);const p=S.pieces[index],clone=el.cloneNode(true),r=el.getBoundingClientRect(),g=geo();clone.classList.add('moving');clone.style.width=r.width+'px';clone.style.height=r.height+'px';clone.style.left='0';clone.style.top='0';document.body.appendChild(clone);S.drag={index,piece:p,el:clone,row:null,col:null,valid:false,dx:r.width/2,dy:r.height/2,g,lift:Math.max(70,g.cell*1.72),raf:0,pending:{x:e.clientX,y:e.clientY},lastKey:'',lastGood:null};schedule(e);addEventListener('pointermove',schedule,{passive:false});addEventListener('pointerup',end,{once:true});addEventListener('pointercancel',end,{once:true})};
function schedule(e){if(!S.drag)return;e.preventDefault();S.drag.pending={x:e.clientX,y:e.clientY};if(S.drag.raf)return;S.drag.raf=requestAnimationFrame(()=>{if(!S.drag)return;S.drag.raf=0;process(S.drag.pending.x,S.drag.pending.y)})}
function process(x,y){const d=S.drag;if(!d)return;const sh=N.SHAPES[d.piece.shapeId];d.el.style.transform=`translate3d(${x-d.dx}px,${y-d.dy-d.lift}px,0) scale(1.1)`;const pos=nearest(sh,x,y-d.lift*.8,d.g)||{row:-99,col:-99,valid:false};d.row=pos.row;d.col=pos.col;d.valid=!!pos.valid;if(d.valid)d.lastGood={row:d.row,col:d.col,x,y};const k=`${d.row}:${d.col}:${d.valid}`;if(k!==d.lastKey){d.lastKey=k;ghost(sh,d.row,d.col,N.blockColor(d.piece.colorIndex),d.valid)}}
async function end(e){if(!S.drag)return;removeEventListener('pointermove',schedule);const d=S.drag;if(d.raf)cancelAnimationFrame(d.raf);if(e&&Number.isFinite(e.clientX))process(e.clientX,e.clientY);clearGhost();S.drag=null;d.el.classList.add('dropAway');setTimeout(()=>d.el.remove(),90);if(!d.valid&&d.lastGood&&e&&Math.hypot(e.clientX-d.lastGood.x,e.clientY-d.lastGood.y)<d.g.step*1.15){d.row=d.lastGood.row;d.col=d.lastGood.col;d.valid=true}if(d.valid)await N.place(d.index,d.row,d.col);else N.sfx('pickup',.18,.82)}
N.addScore=n=>{const inc=Math.round(n*(S.mode==='rush'?1.25:1));S.score+=inc;$('score').textContent=S.score;if(S.score>N.profile.best){N.profile.best=S.score;$('best').textContent=S.score;$('menuBest').textContent=S.score;$('rankBest').textContent=S.score}return inc};
N.scorePunch=(text,kind='normal')=>{const d=document.createElement('div');d.className=`scorePunch ${kind}`;d.textContent=text;boardWrap.appendChild(d);requestAnimationFrame(()=>d.classList.add('go'));setTimeout(()=>d.remove(),720)};
N.place=async(index,row,col)=>{if(S.busy)return;const p=S.pieces[index];if(!p)return;const sh=N.SHAPES[p.shapeId];if(p.used||!N.canPlace(sh,row,col))return;S.busy=true;sh.forEach(([x,y],k)=>{const i=(row+y)*8+(col+x),el=S.cells[i];S.board[i]=p.colorIndex;el.classList.add('filled','slam');el.style.setProperty('--block',N.blockColor(p.colorIndex));el.style.setProperty('--slam-delay',`${k*12}ms`);setTimeout(()=>el.classList.remove('slam'),300+k*12)});p.used=true;N.addScore(sh.length*8);N.sfx('place',.7,.96+Math.random()*.08);N.vibrate(10);boardWrap.classList.add('microKick');setTimeout(()=>boardWrap.classList.remove('microKick'),110);N.renderTray();await resolve();if(S.pieces.every(q=>q.used))N.refill();N.saveActive();S.busy=false;setTimeout(N.checkGameOver,18)};
function lines(){const rows=[],cols=[];for(let r=0;r<8;r++){let ok=true;for(let c=0;c<8;c++)if(!S.board[r*8+c]){ok=false;break}if(ok)rows.push(r)}for(let c=0;c<8;c++){let ok=true;for(let r=0;r<8;r++)if(!S.board[r*8+c]){ok=false;break}if(ok)cols.push(c)}return{rows,cols}}
function debris(el,color,budget,p=1){if(budget.left<=0)return;const er=el.getBoundingClientRect(),wr=boardWrap.getBoundingClientRect(),x=er.left-wr.left+er.width/2,y=er.top-wr.top+er.height/2,count=N.LOW?1:Math.min(3,p+1);for(let j=0;j<count&&budget.left>0;j++,budget.left--){const f=document.createElement('i');f.className='frag v6frag';f.style.left=x+'px';f.style.top=y+'px';f.style.setProperty('--frag',color);const a=Math.random()*Math.PI*1.7-Math.PI*.85,dist=28+Math.random()*42+p*6;f.style.setProperty('--dx',Math.cos(a)*dist+'px');f.style.setProperty('--dy',(Math.sin(a)*dist-18)+'px');f.style.setProperty('--rot',(Math.random()*440-220)+'deg');particles.appendChild(f);setTimeout(()=>f.remove(),620)}}
async function resolve(){const L=lines(),n=L.rows.length+L.cols.length;if(!n){S.combo=0;return}const set=new Set();L.rows.forEach(r=>{for(let c=0;c<8;c++)set.add(r*8+c)});L.cols.forEach(c=>{for(let r=0;r<8;r++)set.add(r*8+c)});S.combo++;const base=n*100+set.size*10+(S.combo-1)*90,inc=N.addScore(base);$('combo').textContent=n>=3?`MEGA CLEAR ×${n}`:S.combo>1?`COMBO ×${S.combo}`:'PERFECT LINE';$('combo').classList.remove('show');void $('combo').offsetWidth;$('combo').classList.add('show');N.sfx(n>1||S.combo>1?'combo':'clear',.82,1+Math.min(n,3)*.025);N.vibrate(n>=2?[18,18,28]:16);clearFlash.classList.remove('pulse');void clearFlash.offsetWidth;clearFlash.classList.add('pulse');const order=[...set].sort((a,b)=>(Math.floor(a/8)+a%8)-(Math.floor(b/8)+b%8));order.forEach((i,k)=>{const el=S.cells[i];el.classList.add('preClear');el.style.setProperty('--clear-delay',`${Math.min(k,14)*11}ms`)});await N.wait(95);boardWrap.classList.remove('impactShake');void boardWrap.offsetWidth;boardWrap.classList.add('impactShake');const budget={left:N.LOW?14:34};order.forEach((i,k)=>setTimeout(()=>{S.cells[i].classList.remove('preClear');S.cells[i].classList.add('clearing');debris(S.cells[i],N.blockColor(S.board[i]),budget,n)},Math.min(k,14)*9));N.scorePunch(`+${inc}`,n>1?'big':'normal');await N.wait(300+Math.min(order.length,14)*7);for(const i of set)S.board[i]=0;N.renderBoard();if(S.board.every(v=>!v)){N.addScore(500);N.profile.perfects++;S.coins+=25;N.sfx('perfect',.9);N.vibrate([24,24,45]);N.scorePunch('PERFECT CLEAR +500','perfect');const next=(S.theme+1)%N.THEMES.length;if(!N.profile.ownedThemes.includes(next))N.profile.ownedThemes.push(next);N.profile.equippedTheme=next;N.applyTheme(next,true)}N.saveProfile();N.saveActive()}
N.checkGameOver=()=>{if(S.finished||S.busy)return;const active=S.pieces.filter(p=>!p.used);if(active.some(p=>{const sh=N.SHAPES[p.shapeId];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(N.canPlace(sh,r,c))return true;return false}))return;N.finish(false)};
N.saveActive=()=>{if(S.mode!=='classic'||S.finished)return;try{localStorage.setItem('novaActiveRunV6',JSON.stringify({mode:'classic',board:S.board,pieces:S.pieces,score:S.score,date:Date.now()}))}catch{}};
N.useShuffle=()=>{if(S.busy||S.blast)return;if(N.profile.boosters.shuffle<=0){N.toast('Kein Shuffle mehr');return}N.profile.boosters.shuffle--;for(let i=0;i<S.pieces.length;i++)if(!S.pieces[i].used)S.pieces[i]=N.randomPiece();N.renderTray();N.saveProfile();N.saveActive();N.sfx('pickup',.5,1.1);N.toast('Pieces gemischt')};
N.armBlast=()=>{if(S.busy)return;if(N.profile.boosters.blast<=0){N.toast('Kein Blast mehr');return}S.blast=!S.blast;$('blastBtn').classList.toggle('armed',S.blast);for(let i=0;i<64;i++)S.cells[i].classList.toggle('blastTarget',S.blast&&!!S.board[i]);N.toast(S.blast?'Tippe einen Block':'Blast abgebrochen')};
N.useBlast=async center=>{if(!S.blast||N.profile.boosters.blast<=0||S.busy)return;S.busy=true;S.blast=false;$('blastBtn').classList.remove('armed');N.profile.boosters.blast--;const cr=Math.floor(center/8),cc=center%8,rm=[];for(let r=cr-1;r<=cr+1;r++)for(let c=cc-1;c<=cc+1;c++)if(r>=0&&r<8&&c>=0&&c<8&&S.board[r*8+c])rm.push(r*8+c);const budget={left:18};for(const i of rm){debris(S.cells[i],N.blockColor(S.board[i]),budget,2);S.cells[i].classList.add('clearing')}N.sfx('combo',.75,.86);await N.wait(230);for(const i of rm)S.board[i]=0;N.renderBoard();N.saveProfile();N.saveActive();S.busy=false;N.toast(`${rm.length} Blöcke entfernt`)};
})();